export interface Database {
  public: {
    Tables: {
      candidate_submissions: {
        Row: {
          id: string;
          full_name: string;
          email: string;
          role1_company: string | null;
          role1_title: string | null;
          role1_duration: string | null;
          role1_scope: string | null;
          role1_rating: number;
          role1_supervisor: string | null;
          role2_company: string | null;
          role2_title: string | null;
          role2_duration: string | null;
          role2_scope: string | null;
          role2_rating: number;
          role2_supervisor: string | null;
          role3_company: string | null;
          role3_title: string | null;
          role3_duration: string | null;
          role3_scope: string | null;
          role3_rating: number;
          role3_supervisor: string | null;
          reference_check_consent: string | null;
          reference_check_explanation: string | null;
          ai_arch_rating: number;
          ai_arch_recent_experience: string | null;
          ai_arch_models_frameworks: string | null;
          b2c_growth_rating: number;
          b2c_growth_best_achievement: string | null;
          b2c_growth_largest_userbase: string | null;
          mobile_rating: number;
          mobile_apps_launched: number;
          mobile_downloads: string | null;
          privacy_rating: number;
          privacy_challenge: string | null;
          privacy_compliance_experience: string | null;
          beta_product: string | null;
          beta_company: string | null;
          beta_participants: number;
          beta_metrics: string | null;
          beta_pivot: string | null;
          beta_involvement: string | null;
          prioritization_privacy: number;
          prioritization_ai: number;
          prioritization_ux: number;
          prioritization_growth: number;
          prioritization_revenue: number;
          prioritization_explanation: string | null;
          scenario_response: string | null;
          transformative_thinking: string | null;
          sovereignty_philosophy: string | null;
          competitive_differentiation: string | null;
          impact_plan_1: string | null;
          impact_plan_2: string | null;
          impact_plan_3: string | null;
          critical_q1: string | null;
          critical_q2: string | null;
          critical_q3: string | null;
          employment_status: string | null;
          notice_period: string | null;
          available_by_july15: boolean;
          contract_to_hire: boolean;
          comp_alignment: string | null;
          remote_work_excellence: string | null;
          unique_edge: string | null;
          evidence_link1: string | null;
          evidence_link2: string | null;
          evidence_link3: string | null;
          vendor_experience: string | null;
          vendor_metrics: string | null;
          vendor_escalation: string | null;
          declaration_accurate: boolean;
          declaration_excited: boolean;
          declaration_understands_excellence: boolean;
          declaration_accountable: boolean;
          digital_signature: string | null;
          submission_date: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          full_name: string;
          email: string;
          role1_company?: string | null;
          role1_title?: string | null;
          role1_duration?: string | null;
          role1_scope?: string | null;
          role1_rating?: number;
          role1_supervisor?: string | null;
          role2_company?: string | null;
          role2_title?: string | null;
          role2_duration?: string | null;
          role2_scope?: string | null;
          role2_rating?: number;
          role2_supervisor?: string | null;
          role3_company?: string | null;
          role3_title?: string | null;
          role3_duration?: string | null;
          role3_scope?: string | null;
          role3_rating?: number;
          role3_supervisor?: string | null;
          reference_check_consent?: string | null;
          reference_check_explanation?: string | null;
          ai_arch_rating?: number;
          ai_arch_recent_experience?: string | null;
          ai_arch_models_frameworks?: string | null;
          b2c_growth_rating?: number;
          b2c_growth_best_achievement?: string | null;
          b2c_growth_largest_userbase?: string | null;
          mobile_rating?: number;
          mobile_apps_launched?: number;
          mobile_downloads?: string | null;
          privacy_rating?: number;
          privacy_challenge?: string | null;
          privacy_compliance_experience?: string | null;
          beta_product?: string | null;
          beta_company?: string | null;
          beta_participants?: number;
          beta_metrics?: string | null;
          beta_pivot?: string | null;
          beta_involvement?: string | null;
          prioritization_privacy?: number;
          prioritization_ai?: number;
          prioritization_ux?: number;
          prioritization_growth?: number;
          prioritization_revenue?: number;
          prioritization_explanation?: string | null;
          scenario_response?: string | null;
          transformative_thinking?: string | null;
          sovereignty_philosophy?: string | null;
          competitive_differentiation?: string | null;
          impact_plan_1?: string | null;
          impact_plan_2?: string | null;
          impact_plan_3?: string | null;
          critical_q1?: string | null;
          critical_q2?: string | null;
          critical_q3?: string | null;
          employment_status?: string | null;
          notice_period?: string | null;
          available_by_july15?: boolean;
          contract_to_hire?: boolean;
          comp_alignment?: string | null;
          remote_work_excellence?: string | null;
          unique_edge?: string | null;
          evidence_link1?: string | null;
          evidence_link2?: string | null;
          evidence_link3?: string | null;
          vendor_experience?: string | null;
          vendor_metrics?: string | null;
          vendor_escalation?: string | null;
          declaration_accurate?: boolean;
          declaration_excited?: boolean;
          declaration_understands_excellence?: boolean;
          declaration_accountable?: boolean;
          digital_signature?: string | null;
          submission_date?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string;
          email?: string;
          role1_company?: string | null;
          role1_title?: string | null;
          role1_duration?: string | null;
          role1_scope?: string | null;
          role1_rating?: number;
          role1_supervisor?: string | null;
          role2_company?: string | null;
          role2_title?: string | null;
          role2_duration?: string | null;
          role2_scope?: string | null;
          role2_rating?: number;
          role2_supervisor?: string | null;
          role3_company?: string | null;
          role3_title?: string | null;
          role3_duration?: string | null;
          role3_scope?: string | null;
          role3_rating?: number;
          role3_supervisor?: string | null;
          reference_check_consent?: string | null;
          reference_check_explanation?: string | null;
          ai_arch_rating?: number;
          ai_arch_recent_experience?: string | null;
          ai_arch_models_frameworks?: string | null;
          b2c_growth_rating?: number;
          b2c_growth_best_achievement?: string | null;
          b2c_growth_largest_userbase?: string | null;
          mobile_rating?: number;
          mobile_apps_launched?: number;
          mobile_downloads?: string | null;
          privacy_rating?: number;
          privacy_challenge?: string | null;
          privacy_compliance_experience?: string | null;
          beta_product?: string | null;
          beta_company?: string | null;
          beta_participants?: number;
          beta_metrics?: string | null;
          beta_pivot?: string | null;
          beta_involvement?: string | null;
          prioritization_privacy?: number;
          prioritization_ai?: number;
          prioritization_ux?: number;
          prioritization_growth?: number;
          prioritization_revenue?: number;
          prioritization_explanation?: string | null;
          scenario_response?: string | null;
          transformative_thinking?: string | null;
          sovereignty_philosophy?: string | null;
          competitive_differentiation?: string | null;
          impact_plan_1?: string | null;
          impact_plan_2?: string | null;
          impact_plan_3?: string | null;
          critical_q1?: string | null;
          critical_q2?: string | null;
          critical_q3?: string | null;
          employment_status?: string | null;
          notice_period?: string | null;
          available_by_july15?: boolean;
          contract_to_hire?: boolean;
          comp_alignment?: string | null;
          remote_work_excellence?: string | null;
          unique_edge?: string | null;
          evidence_link1?: string | null;
          evidence_link2?: string | null;
          evidence_link3?: string | null;
          vendor_experience?: string | null;
          vendor_metrics?: string | null;
          vendor_escalation?: string | null;
          declaration_accurate?: boolean;
          declaration_excited?: boolean;
          declaration_understands_excellence?: boolean;
          declaration_accountable?: boolean;
          digital_signature?: string | null;
          submission_date?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}